### ISSUE TITLE
catapulte Issue on Mac M2 Architecture: GLIBC Version Not Found

### ISSUE THREAD

**Issue by PepperPlatypus** [jdrouet/catapulte#700]
#### Description:
I've been encountering an issue with `catapulte` on a Mac with M2 architecture. This problem seems to be related to the absence of a specific version of the GNU C Library (`GLIBC`) required by `catapulte`. I've noticed similar issues in my own Rust projects, indicating that this might not be isolated to `catapulte`.

#### Error Message:
```
/usr/bin/catapulte: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/catapulte)
```

#### Steps to Reproduce:
```yaml
version: '3'

services:
  catapulte:
    image: jdrouet/catapulte:latest
    container_name: catapulte
    environment:
      - SMTP_HOSTNAME=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_USERNAME=donnell.konopelski65@ethereal.email 
      - SMTP_PASSWORD=nYSncuFYzZ7mMwWRHa
      - SMTP_TLS_ENABLED=false
      - SWAGGER_ENABLED=true
      - TEMPLATE_PROVIDER=local
      - TEMPLATE_ROOT=/templates
    ports:
      - "3000:3000"
    volumes:
      - ./templates:/templates:ro
```
#### Expected Behavior:
`catapulte` should run without encountering the `GLIBC_2.32` version not found error.

#### Actual Behavior:
The application fails to start due to the missing `GLIBC_2.32` version.

#### Additional Context:
This issue does not seem to be specific to `catapulte`, as I've encountered similar problems in my Rust projects. It appears to be related to the compatibility of certain libraries with the M2 architecture.

#### Potential Solution:
If I manage to find a workaround or solution, I will update this issue accordingly.
